// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbsQQhgEkbNOW-VYrlfvZcDG5n6L2uCMI',
    appId: '1:118630022353:web:513ab9170bf69557fad9f0',
    messagingSenderId: '118630022353',
    projectId: 'smart-chat-app-c0389',
    authDomain: 'smart-chat-app-c0389.firebaseapp.com',
    storageBucket: 'smart-chat-app-c0389.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZj32nonviQXesmjkrFk1OvAtbiYTkbRE',
    appId: '1:118630022353:android:96bc3b07715a3862fad9f0',
    messagingSenderId: '118630022353',
    projectId: 'smart-chat-app-c0389',
    storageBucket: 'smart-chat-app-c0389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5gZtKnbhtD4KIYf7DJb7DsDS54srcGo',
    appId: '1:118630022353:ios:f5448c2247109253fad9f0',
    messagingSenderId: '118630022353',
    projectId: 'smart-chat-app-c0389',
    storageBucket: 'smart-chat-app-c0389.firebasestorage.app',
    iosBundleId: 'com.example.smartChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5gZtKnbhtD4KIYf7DJb7DsDS54srcGo',
    appId: '1:118630022353:ios:f5448c2247109253fad9f0',
    messagingSenderId: '118630022353',
    projectId: 'smart-chat-app-c0389',
    storageBucket: 'smart-chat-app-c0389.firebasestorage.app',
    iosBundleId: 'com.example.smartChatApp',
  );
}
